"""Mode classification, checked against excerpts of the real policies (tests/fixtures/policy)."""

from pathlib import Path

import pytest

from scout import policy

FIX = Path(__file__).parent / "fixtures" / "policy"


def read(*names: str) -> str:
    return "\n\n".join((FIX / n).read_text() for n in names)


def modes(r: dict) -> tuple:
    return r["mode"], r["ai_posts_forbidden"], r["disclosure_required"]


def test_duckdb_is_pair():
    # "AI as tools for coding is welcome" + comments/PR body by humans + no autonomous agents
    r = policy.classify(read("duckdb_AI_POLICY.md", "duckdb_CONTRIBUTING.md"))
    assert modes(r) == ("pair", True, False)
    assert r["ai"] != "restrictive"


def test_duckdb_contributing_alone_is_a_plain_ban():
    # without the AI_POLICY.md allowance, "do not submit PRs generated by AI" is a ban
    assert policy.classify(read("duckdb_CONTRIBUTING.md"))["mode"] == "own"


def test_llama_cpp_is_pair():
    # "AI-generated code is allowed", disclosure required, AI-written posts and automated PRs prohibited
    r = policy.classify(read("llama_CONTRIBUTING.md", "llama_AGENTS.md"))
    assert modes(r) == ("pair", True, True)


def test_f3d_is_pair():
    # disclosed, reviewed AI code is fine; AI-written issues, PRs and communication are not
    r = policy.classify(read("f3d_AI_POLICY.md"))
    assert modes(r) == ("pair", True, True)


def test_plain_project_is_draft():
    r = policy.classify(read("plain_CONTRIBUTING.md"))
    assert modes(r) == ("draft", False, False)
    assert r["ai"] == "none"


@pytest.mark.parametrize("text", [
    "We do not accept pull requests generated by AI tools.",
    "AI-generated contributions are not welcome here.",
    "Code written by AI assistants will not be merged.",
    "Contributions written with LLMs are not allowed.",
])
def test_outright_bans_are_own(text):
    r = policy.classify(text)
    assert r["mode"] == "own" and r["ai"] == "restrictive" and r["ai_posts_forbidden"]


@pytest.mark.parametrize("text,expected", [
    ("If you used AI assistance, please disclose it in the PR description.", ("draft", False, True)),
    ("You may use AI tools. You don't have to disclose it.", ("draft", False, False)),
    ("AI tools are welcome. Autonomous agents are not allowed.", ("pair", False, False)),
    ("Using LLMs as tools for coding is fine. Comments must be written by humans.", ("pair", True, False)),
    ("Please write the PR description in your own words. We use AI a lot.", ("pair", True, False)),
    ("AI-assisted contributions are welcome but do not submit pull requests generated by AI.", ("pair", False, False)),
])
def test_sentence_rules(text, expected):
    assert modes(policy.classify(text)) == expected


def test_a_ban_on_missing_disclosure_is_not_a_ban_on_code():
    text = "AI-generated code is allowed. Undisclosed AI usage may result in a permanent ban."
    assert modes(policy.classify(text)) == ("draft", False, True)


def test_unchanged_keys_stay():
    r = policy.classify("Just open a PR.")
    assert set(r) >= {"ai", "evidence", "cla", "mode", "ai_posts_forbidden", "disclosure_required"}
