import urllib.parse
from datetime import datetime, timedelta, timezone

import pytest

from scout import config, filters, policy, rank, score, track
from scout.github import GitHub, NotFound

NOW = datetime(2026, 9, 26, tzinfo=timezone.utc)


def iso(days_ago: float) -> str:
    return (NOW - timedelta(days=days_ago)).isoformat().replace("+00:00", "Z")


class Fake:
    """Transport that serves canned responses by path prefix."""

    def __init__(self, routes: dict):
        self.routes = routes
        self.seen = []

    def __call__(self, path: str):
        self.seen.append(path)
        base, _, query = path.partition("?")
        if base in self.routes:
            params = dict(urllib.parse.parse_qsl(query))
            if int(params.get("page", 1)) > 1:
                return []
            return self.routes[base]
        raise NotFound(path)


@pytest.fixture
def cfg():
    return config.load()


# -- policy -----------------------------------------------------------------

@pytest.mark.parametrize("text,expected", [
    ("We do not accept pull requests generated by AI tools.", "restrictive"),
    ("Please do not submit pull requests generated by AI (LLMs).", "restrictive"),
    ("Code written by AI assistants will not be merged.", "restrictive"),
    ("AI-generated contributions are not welcome here.", "restrictive"),
    ("PRs written with LLMs will be closed without review.", "restrictive"),
    ("If you used AI assistance, please disclose it in the PR description.", "disclosure"),
    ("Contributions made with Copilot must be disclosed.", "disclosure"),
    ("We are an AI company building inference engines.", "mentioned"),
    ("Please run the tests before opening a PR. Use a cursor to iterate.", "none"),
    ("We use AI a lot. You don't have to disclose your usage of AI.", "mentioned"),
])
def test_policy_classify(text, expected):
    assert policy.classify(text)["ai"] == expected


def test_policy_cla():
    assert policy.classify("You must sign our Contributor License Agreement.")["cla"]
    assert not policy.classify("Just open a PR.")["cla"]


# -- scoring ----------------------------------------------------------------

def test_scale_bounds():
    assert score._scale(1, good=2, bad=60) == 1.0
    assert score._scale(60, good=2, bad=60) == 0.0
    assert 0 < score._scale(10, good=2, bad=60) < 1
    assert score._scale(None, good=2, bad=60) == 0.5


def test_is_outside_ignores_bots_and_members():
    assert score.is_outside({"author_association": "CONTRIBUTOR", "user": {"type": "User"}})
    assert not score.is_outside({"author_association": "MEMBER", "user": {"type": "User"}})
    assert not score.is_outside({"author_association": "NONE", "user": {"type": "Bot"}})


def test_measure_friendly_repo(monkeypatch):
    prs = [{"number": i, "author_association": "CONTRIBUTOR", "user": {"login": f"u{i}", "type": "User"},
            "created_at": iso(10), "merged_at": iso(8) if i % 5 else None} for i in range(10)]
    routes = {"repos/o/r": {"stargazers_count": 999, "language": "C++", "pushed_at": iso(1),
                            "owner": {"type": "Organization"}},
              "repos/o/r/pulls": prs}
    for p in prs:
        routes[f"repos/o/r/issues/{p['number']}/comments"] = [
            {"user": {"login": "maint", "type": "User"}, "author_association": "MEMBER",
             "created_at": iso(9.5)}]
    monkeypatch.setattr(policy, "fetch", lambda gh, repo: {"ai": "none", "evidence": "", "cla": False, "files": []})
    m = score.measure(GitHub(transport=Fake(routes)), "o/r", now=NOW)
    assert m["merge_rate"] == pytest.approx(0.8)
    assert m["median_days_to_merge"] == pytest.approx(2)
    assert m["median_hours_to_first_response"] == pytest.approx(12)
    assert m["confident"] and m["friendliness"] > 0.8


def test_frequent_contributor_counts_as_staff():
    pr = {"author_association": "CONTRIBUTOR", "user": {"login": "nathan-TT", "type": "User"}}
    assert score.is_outside(pr, {"nathan-TT": 1})
    assert not score.is_outside(pr, {"nathan-TT": 5})
    assert score.is_outside({"author_association": "FIRST_TIME_CONTRIBUTOR",
                             "user": {"login": "x", "type": "User"}}, {"x": 9})


def test_same_repo_branch_means_staff():
    fork = {"author_association": "CONTRIBUTOR", "user": {"login": "a", "type": "User"},
            "head": {"repo": {"full_name": "someone/tt-metal"}}}
    branch = {**fork, "head": {"repo": {"full_name": "tenstorrent/tt-metal"}}}
    deleted = {**fork, "head": {"repo": None}}
    assert score.is_outside(fork, {}, "tenstorrent/tt-metal")
    assert not score.is_outside(branch, {}, "tenstorrent/tt-metal")
    assert score.is_outside(deleted, {}, "tenstorrent/tt-metal")


def test_merges_elsewhere_is_neutral_not_zero(monkeypatch):
    prs = [{"number": i, "author_association": "NONE", "user": {"login": f"u{i}", "type": "User"},
            "created_at": iso(10), "merged_at": None} for i in range(25)]
    routes = {"repos/o/r": {"pushed_at": iso(1)}, "repos/o/r/pulls": prs}
    monkeypatch.setattr(policy, "fetch", lambda gh, repo: {"ai": "none", "evidence": "", "cla": False, "files": []})
    m = score.measure(GitHub(transport=Fake(routes)), "o/r", now=NOW)
    assert m["merges_elsewhere"] and m["friendliness"] >= 0.35


def test_measure_too_few_prs_is_neutral(monkeypatch):
    routes = {"repos/o/r": {"pushed_at": iso(1)}, "repos/o/r/pulls": []}
    monkeypatch.setattr(policy, "fetch", lambda gh, repo: {"ai": "none", "evidence": "", "cla": False, "files": []})
    m = score.measure(GitHub(transport=Fake(routes)), "o/r", now=NOW)
    assert not m["confident"] and m["friendliness"] == 0.5


# -- ranking ----------------------------------------------------------------

def issue(**kw):
    base = {"key": "duckdb/duckdb#1", "repo": "duckdb/duckdb", "number": 1, "title": "t",
            "created_at": iso(2), "label_groups": ["confirmed_bug"], "labels": ["reproduced"],
            "comments": 2, "assignees": []}
    return {**base, **kw}


def test_tier_outranks_discovery(cfg):
    repo = {"friendliness": 0.7, "language": "C++", "ai_policy": "none", "stars": 5000}
    tiered = rank.score_issue(issue(), repo, cfg, {}, now=NOW)
    found = rank.score_issue(issue(repo="nobody/thing", key="nobody/thing#1"), repo, cfg, {}, now=NOW)
    assert tiered["score"] > found["score"]
    assert found["tier"] == "Discovered"


def test_restrictive_policy_sinks(cfg):
    ok = rank.score_issue(issue(), {"friendliness": 0.7, "ai_policy": "none"}, cfg, {}, now=NOW)
    bad = rank.score_issue(issue(), {"friendliness": 0.7, "ai_policy": "restrictive"}, cfg, {}, now=NOW)
    assert bad["score"] == pytest.approx(ok["score"] * 0.6, abs=0.2)


def test_home_project_bonus(cfg):
    st = {"contributions": {"per_repo": {"duckdb/duckdb": {"merged": 2}}}}
    base = rank.score_issue(issue(), {"friendliness": 0.7}, cfg, {}, now=NOW)["score"]
    home = rank.score_issue(issue(), {"friendliness": 0.7}, cfg, st, now=NOW)["score"]
    assert home > base


def test_eligibility(cfg):
    assert rank.eligible(issue(), {}, cfg, {}, now=NOW) is None
    assert rank.eligible(issue(), {}, cfg, {"suggestions": {"duckdb/duckdb#1": {}}}, now=NOW) == "already suggested"
    assert rank.eligible(issue(assignees=["x"]), {}, cfg, {}, now=NOW) == "assigned"
    assert rank.eligible(issue(created_at=iso(400)), {}, cfg, {}, now=NOW) == "too old"
    assert rank.eligible(issue(labels=["wontfix"]), {}, cfg, {}, now=NOW).startswith("label")
    assert rank.eligible(issue(repo="a/b", key="a/b#1"), {"stars": 10}, cfg, {}, now=NOW) == "too few stars"


def test_label_groups(cfg):
    from scout.discover import label_groups_for
    assert "beginner" in label_groups_for("Good First Issue", cfg)
    assert "beginner" in label_groups_for("E-easy", cfg)
    assert "help" in label_groups_for("help-wanted", cfg)
    assert "bounty" in label_groups_for("💎 Bounty", cfg)
    assert label_groups_for("needs triage", cfg) == []


# -- claims / linked PRs ----------------------------------------------------

def test_activity_detects_claims_and_prs():
    timeline = [
        {"event": "commented", "author_association": "NONE", "user": {"login": "someone"},
         "created_at": iso(3), "body": "Hi, I'd like to work on this!"},
        {"event": "commented", "author_association": "NONE", "user": {"login": "old"},
         "created_at": iso(60), "body": "can I take this?"},
        {"event": "cross-referenced", "source": {"issue": {"pull_request": {}, "state": "open",
                                                           "html_url": "https://x/pull/9"}}},
    ]
    gh = GitHub(transport=Fake({"repos/o/r/issues/1/timeline": timeline}))
    act = filters.activity(gh, "o/r", 1, claim_window_days=21, now=NOW)
    assert act["linked_open_prs"] == ["https://x/pull/9"]
    assert [c["by"] for c in act["recent_claims"]] == ["someone"]


@pytest.mark.parametrize("body,claim", [
    ("I'll take a look at this", True),
    ("Please assign this to me", True),
    ("I'm working on it", True),
    ("This also happens on Linux", False),
    ("Can I ask why this is needed?", False),
])
def test_claim_regex(body, claim):
    assert bool(filters.CLAIM.search(body)) == claim


# -- tracking ---------------------------------------------------------------

def test_ladder():
    assert track.ladder(0, False) == "Getting started"
    assert track.ladder(1, False) == "Contributor"
    assert track.ladder(3, False) == "Regular contributor"
    assert track.ladder(8, False) == "Trusted contributor"
    assert track.ladder(0, True) == "Maintainer"


def test_mentions():
    pr = {"title": "Fix crash", "body": "Fixes #123"}
    assert track._mentions(pr, "o/r", 123)
    assert not track._mentions(pr, "o/r", 12)
    assert track._mentions({"title": "x", "body": "see https://github.com/o/r/issues/7"}, "o/r", 7)
    assert not track._mentions({"title": "x", "body": "other/repo#7"}, "o/r", 7)


def test_update_suggestions_flow():
    st = {"suggestions": {
        "o/r#1": {"repo": "o/r", "number": 1, "status": "suggested", "suggested_at": iso(2)},
        "o/r#2": {"repo": "o/r", "number": 2, "status": "suggested", "suggested_at": iso(2)},
        "o/r#3": {"repo": "o/r", "number": 3, "status": "suggested", "suggested_at": iso(30)},
        "o/r#4": {"repo": "o/r", "number": 4, "status": "suggested", "suggested_at": iso(1)},
    }}
    contrib = {"prs": [{"repo": "o/r", "title": "fix", "body": "Closes #1", "status": "merged",
                        "created_at": iso(1), "url": "u"}],
               "commented_issues": ["o/r#2"]}
    gh = GitHub(transport=Fake({"repos/o/r/issues/3": {"state": "open"},
                                "repos/o/r/issues/4": {"state": "closed"}}))
    track.update_suggestions(gh, st, contrib, skip_after_days=14, now=NOW)
    s = st["suggestions"]
    assert s["o/r#1"]["status"] == "merged"
    assert s["o/r#2"]["status"] == "claimed"
    assert s["o/r#3"]["status"] == "skipped"
    assert s["o/r#4"]["status"] == "taken"
    assert s["o/r#1"]["history"][-1] == {"at": NOW.isoformat(timespec="seconds"),
                                         "from": "suggested", "to": "merged"}
